version: "3.3"

services:

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    env_file:
      - .env

  db:
    image: postgres:15.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  server:
    build:
      context: ./backend
    image: backend
    environment:
      - PYTHONPATH=/usr/src/backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/usr/src/backend
    restart: always
    env_file:
      - .env
    command: uvicorn main:app --host=0.0.0.0 --port=8001 --reload
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "10"

volumes:
  postgres_data: